"""empty message

Revision ID: eae45cedca3c
Revises: 942391bb6d93
Create Date: 2024-06-13 15:39:42.744016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eae45cedca3c'
down_revision = '942391bb6d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=False))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
